### ISSUE TITLE
'class PWMDirectMatrix' has no member named 'drawRGBBitmap'

### ISSUE THREAD

**Issue by nanu-c** [marcmerlin/LED-Matrix#1]
The line:

```
    matrix->drawRGBBitmap(0, 0, RGB_bmp[i], 8, 8);
```

produces following error

```
directmatrix8x8_tricolor_direct_sr.ino: In function 'void loop()':
directmatrix8x8_tricolor_direct_sr:235: error: 'class PWMDirectMatrix' has no member named 'drawRGBBitmap'
'class PWMDirectMatrix' has no member named 'drawRGBBitmap'
```

**Comment by TheDukeZip** [comment]
This is an old issue and you've probably moved on, but for future reference if someone else has the same issue:

The function isn't included in Adafruit's GFX library but marcmerlin added it to his fork. You can use his version or at least copy and paste the function into your copy of the GFX library. https://github.com/marcmerlin/Adafruit-GFX-Library

**Comment by marcmerlin** [comment]
My apologies, I somehow never got Email on the first issue from @nanu-c . Thanks for answering @TheDukeZip

**Comment by pacav69** [comment]
After so many years this is still an issue so to speak.

**Comment by marcmerlin** [comment]
Ok, this is useless spam, please stop.
