### ISSUE TITLE
hobbyking

### ISSUE THREAD

**Issue by pacav69** [marcmerlin/LED-Matrix#2]
the hobbyking link doesn't work

**Comment by marcmerlin** [comment]
they stopped selling it. If you find other links, I'm happy to add them.

**Comment by pacav69** [comment]
they are not selling the item anymore perhaps not a good seller. 

i just thought you could remove it from your readme.

**Comment by marcmerlin** [comment]
My apologies for doing this so late, some of my Email got lost. Done.
