### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by pacav69** [marcmerlin/LED-Matrix#3]
i recommend adding install instructions to the readme.md

Also add header text to the 'Required libraries:' so that it stands out and displays like this
'

**Comment by marcmerlin** [comment]
2nd part done.
Install instructions, I'm not going to spend my time on that. It's not a beginner library at all, it's really meant for people who understand the basics of shift registers and wiring. If they can do that, they can install libraries :)

**Comment by pacav69** [comment]
i almost missed the additional libraries part as i only noticed it after i compiled the example.
i thought you may say that, i did think of that latter your library is more for experienced users but arduino is supposed to be targeting people who just want to play :)

ps keep up the great work
