### ISSUE TITLE
the code

### ISSUE THREAD

**Issue by hek12345** [marcmerlin/LED-Matrix#4]
whenever i run the code in the example files it says "exit status 1 expected '}' at the end on the input"
can you please fix or tell me how to fix it?

**Comment by marcmerlin** [comment]
Sorry that I never saw this message. There is totally not enough info for anyone to be able to answer your question.
How can I know which code you ran?
What platform did you compile on?  
What's the full compile output with error output?
etc...

**Comment by marcmerlin** [comment]
please reopen if you have actionable info
