### ISSUE TITLE
Exposing R0, G0, etc... to user

### ISSUE THREAD

**Issue by AndyEngland521** [marcmerlin/LED-Matrix#5]
Hi Marc, This code is extraordinarily difficult to port to other platforms without the R, G, B data pins exposed to the user. Any way you can have these be user defined instead of having them be contained within the library? Is there a reason that you use specific pins for specific platforms(This is why I didn't make a PR)?

**Comment by marcmerlin** [comment]
@AndyEngland521 can you be more specific?
First, there are no R0 G0 pins, like an RGB Panel, I'm not sure if you were referring to that
Second, my examples do define pins from the caller code. They are not hardcoded in the lib.
https://github.com/marcmerlin/LED-Matrix/blob/master/examples/directmatrix8x8_tricolor_direct_sr/directmatrix8x8_tricolor_direct_sr.ino#L46
